### ISSUE TITLE
QUESTION: I have a problem with large data objects

### ISSUE THREAD

**Issue by Zhuk66** [mschubert/clustermq#146]
When I use large data objects, I am getting this error message in the SLURM log file:
> clustermq:::worker("tcp://xxxxxxxxxx:7350")
2019-05-10 13:38:50.189553 | Master: tcp://xxxxxxxxxxx:7350
2019-05-10 13:38:50.200181 | WORKER_UP to: tcp://xxxxxxxxxxx:7350
2019-05-10 13:38:52.885488 |
Error in switch(msg$id, DO_CALL = { : EXPR must be a length 1 vector
Calls: <Anonymous>
Execution halted

Here is my code example:

```r
library(foreach)
library(clustermq)

myFunc <- function(data)
{
  sum(data)
}

path <- "path/to/slurm.tmpl"
options(
  clustermq.scheduler = "slurm",
  clustermq.template = path
)


testSLURM <- function()
{
  n=3000000
  k=100
  p=100
  mu=0
  sigma=1
  
  m <- matrix(data=rnorm(n*k,mu,sigma), nrow=n, ncol=k)
  
  clustermq::register_dopar_cmq(n_jobs=4)
  
  res <- foreach(i = 1:k,
             .inorder=TRUE,
             .combine = 'c',
             .export = c("m", "%dopar%", "myFunc"),
             .verbose=FALSE) %dopar% {
                   myFunc(m[,i])
             }
  return(res)
}
```

The same code works fine if I call foreach::registerDoSEQ() before foreach()
How can I fix it?

**Comment by mschubert** [comment]
Can you show me your `sessionInfo()` with `clustermq` loaded?

**Comment by Zhuk66** [comment]
> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux

Matrix products: default
BLAS: /opt/revr/ropen/3.4.2/lib64/R/lib/libRblas.so
LAPACK: /opt/revr/ropen/3.4.2/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] clustermq_0.8.7.9000 foreach_1.4.4        purrr_0.3.2          dplyr_0.8.0.1        pryr_0.1.4          
[6] usethis_1.5.0        devtools_2.0.2.9000  RevoUtilsMath_10.0.1

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1         pillar_1.3.1       compiler_3.4.2     prettyunits_1.0.2  remotes_2.0.4.9000
 [6] iterators_1.0.10   tools_3.4.2        testthat_2.0.1     digest_0.6.18      pkgbuild_1.0.3    
[11] pkgload_1.0.2      memoise_1.1.0      tibble_2.1.1       pkgconfig_2.0.2    rlang_0.3.4       
[16] cli_1.1.0          rstudioapi_0.10    withr_2.1.2        stringr_1.4.0      desc_1.2.0        
[21] RevoUtils_10.0.6   fs_1.2.7           rprojroot_1.3-2    tidyselect_0.2.5   glue_1.3.1        
[26] R6_2.4.0           processx_3.3.0     sessioninfo_1.1.1  callr_3.2.0        magrittr_1.5      
[31] backports_1.1.4    codetools_0.2-16   ps_1.3.0           assertthat_0.2.1   stringi_1.4.3     
[36] crayon_1.3.4      
>

**Comment by Zhuk66** [comment]
Michael,

I loaded a develop branch of clusterMQ and called it 0.8.7.9000.

**Comment by Zhuk66** [comment]
The problem seems to be SLURM specific. If I set n_jobs=0, and remove SLURM options:
options(clustermq.scheduler = NULL) and options(clustermq.template = NULL),
everything works fine. I tried to increase 'memory' parameter but it did not help.

**Comment by mschubert** [comment]
This looks like an interrupt problem much more than a data problem.

We [had issues in the past with `SIGWINCH`](https://github.com/ropensci/rzmq/pull/37) that [got fixed in `R>=3.4.3`](https://github.com/wch/r-source/commit/6e325aa1853e6b4e0c8b089e239f952f731d72ed) (I think).

As you are still using `R=3.4.2`, something like this may well be the cause.

Thank you for flagging this. If this is indeed the cause, we should require a more recent R version in `DESCRIPTION`.

Could you try running your example with `R>=3.5.0`, with a smaller data set, and see if the problem persists?

Note that comparing to `n_jobs=0` is problematic, because it will process your calls locally instead of sending them to SLURM jobs (no event loop means there will never be an interrupt of socket polling).

Then there is a couple of likely side issues because of the big data objects that should be tackled separately:

* You send a lot of data (my R session requires 10 GiB of memory for sending the serialized object)
* Your workers may not have enough memory (this should show up in the worker log; I would try 20 GiB first to be sure)
* You may need to increase the worker timeout in your template depending on how fast your network is (how long do you expect your common data transfer to take?)

**Comment by Zhuk66** [comment]
1. Switched to R=3.5.2. Same behavior.
2. Added timeout=20:

Error in master(qsys = workers, iter = df, rettype = rettype, fail_on_error = fail_on_error,  : 
  Socket timeout reached, likely due to a worker crash
8: (function () 
   traceback(2))()
7: stop("Socket timeout reached, likely due to a worker crash")
6: master(qsys = workers, iter = df, rettype = rettype, fail_on_error = fail_on_error, 
       chunk_size = chunk_size, timeout = timeout, max_calls_worker = max_calls_worker)
5: (function (df, fun, const = list(), export = list(), seed = 128965, 
       memory = NULL, template = list(), n_jobs = NULL, job_size = NULL, 
    ...
4: do.call(Q_rows, c(list(df = args_df, fun = fun), data))
3: e$fun(obj, substitute(ex), parent.frame(), e$data)
2: foreach(i = 1:k, .inorder = TRUE, .combine = "c", .export = c("m", 
       "%dopar%", "myFunc"), .verbose = FALSE) %dopar% {
    ... at largeEx.R#44
1: testSLURM()
> 

My parameters:
  n <- 2680000
  k <- 100
  mu <- 0
  sigma <- 1
  m <- matrix(data=rnorm(n*k,mu,sigma), nrow=n, ncol=k)

Arguments passed to clustermq:
 memory  n_jobs timeout 
 "8192"    "11"    "20"

If I reduce n_jobs to 10, everything works fine. Increasing memory parameter does not help. 
> parallel::detectCores()
[1] 56

if I decrease n to 2000000, everything works.

3. I do not understand how can I increase memory limit allocated to each worker. Can you help please?

Here is my sessionInfo():
> sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux

Matrix products: default
BLAS: /opt/revr/ropen/3.5.2/lib64/R/lib/libRblas.so
LAPACK: /opt/revr/ropen/3.5.2/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] doParallel_1.0.14    iterators_1.0.10     coreUtils_1.0.3      clustermq_0.8.7      foreach_1.4.4       
 [6] purrr_0.3.2          dplyr_0.8.0.1        pryr_0.1.4           usethis_1.5.0        devtools_2.0.2      
[11] RevoUtilsMath_11.0.0

loaded via a namespace (and not attached):
 [1] progress_1.2.0          RevoUtils_11.0.2        tidyselect_0.2.5        remotes_2.0.4          
 [5] listenv_0.7.0           testthat_2.0.1          rlang_0.3.4             pkgbuild_1.0.3         
 [9] pillar_1.3.1            glue_1.3.1              withr_2.1.2             DBI_1.0.0              
[13] rappdirs_0.3.1          sessioninfo_1.1.1       stringr_1.4.0           future_1.12.0          
[17] codetools_0.2-16        memoise_1.1.0           callr_3.2.0             ps_1.3.0               
[21] batchtools_0.9.11       rzmq_0.9.6              Rcpp_1.0.1              backports_1.1.4        
[25] checkmate_1.9.1         desc_1.2.0              pkgload_1.0.2           debugme_1.1.0          
[29] doFuture_0.8.0          fs_1.2.7                future.batchtools_0.7.2 brew_1.0-6             
[33] hms_0.4.2               digest_0.6.18           stringi_1.4.3           processx_3.3.0         
[37] rprojroot_1.3-2         cli_1.1.0               tools_3.5.2             magrittr_1.5           
[41] base64url_1.4           tibble_2.1.1            crayon_1.3.4            pkgconfig_2.0.2        
[45] data.table_1.12.2       prettyunits_1.0.2       assertthat_0.2.1        infuser_0.2.8          
[49] rstudioapi_0.10         R6_2.4.0                globals_0.12.4          compiler_3.5.2

**Comment by Zhuk66** [comment]
Tested again with R 3.5.2 and increased memory limit. It worked!

**Comment by Zhuk66** [comment]
I think I ran it with a wrong data set. The problem still exists. Here is my SLURM file example:
#!/bin/sh
#SBATCH --job-name={{ job_name }}
#SBATCH --partition=debug
#SBATCH --output={{ log_file | /path2log/slurm.log }}
#SBATCH --error={{ log_file | /path2log/slurm.log }}
#SBATCH --mem-per-cpu={{ memory | 4096 }}
#SBATCH --array=1-{{ n_jobs }}

ulimit -v $(( 16384 * {{ memory | 4096 }} ))
CMQ_AUTH={{ auth }} R --no-save --no-restore -e 'clustermq:::worker("{{ master }}")'

**Comment by mschubert** [comment]
Can you try with:

```r
Q(..., timeout=7200)
```

and template

```r
CMQ_AUTH={{ auth }} R --no-save --no-restore -e 'clustermq:::worker("{{ master }}", timeout=7200)'
```

and post the worker log if this fails?

**Comment by Zhuk66** [comment]
It failed. Here is my code:

library(foreach)
library(clustermq)

myFunc <- function(data)
{
  sum(data)
}

path <- "path/to/slurm.tmpl"
options(
  clustermq.scheduler = "slurm",
  clustermq.template = path
)
  n <- 3680000
  k <- 100
  p <- 100
  mu <- 0
  sigma <- 1
  
  m <- matrix(data=rnorm(n*k,mu,sigma), nrow=n, ncol=k)
Q(fun, i=1:k, export=list(myFunc=myFunc, m=m), n_jobs=5, timeout=7200)
-----------------
slurm.tmpl:
#!/bin/sh
#SBATCH --job-name={{ job_name }}
#SBATCH --partition=debug
#SBATCH --output={{ log_file | /path2log/slurm.log }}
#SBATCH --error={{ log_file | /path2log/slurm.log }}
#SBATCH --mem-per-cpu={{ memory | 4096 }}
#SBATCH --array=1-{{ n_jobs }}

ulimit -v $(( 16384 * {{ memory | 4096 }} ))
CMQ_AUTH={{ auth }} /opt/R/3.5.2/bin/R --no-save --no-restore -e 'clustermq:::worker("{{ master }}", timeout=7200)'
---------------
slurm.log:
> clustermq:::worker("tcp://host:7336", timeout=7200)
> clustermq:::worker("tcp://host:7336", timeout=7200)
> clustermq:::worker("tcp://host:7336", timeout=7200)
> clustermq:::worker("tcp://host:7336", timeout=7200)
2019-07-05 12:28:51.752560 | Master: tcp://host:7336
2019-07-05 12:28:51.752784 | Master: tcp://host:7336
2019-07-05 12:28:51.754256 | Master: tcp://host:7336
> 2019-07-05 12:28:51.761202 | WORKER_UP to: tcp://host:7336
clustermq:::worker("tcp://host:7336", timeout=7200)
2019-07-05 12:28:51.761211 | WORKER_UP to: tcp://host:7336
2019-07-05 12:28:51.766304 | WORKER_UP to: tcp://host:7336
2019-07-05 12:28:51.777725 | Master: tcp://host:7336
2019-07-05 12:28:51.790752 | WORKER_UP to: tcp://host:7336
2019-07-05 12:28:51.790564 | Master: tcp://host:7336
2019-07-05 12:28:51.799209 | WORKER_UP to: tcp://host:7336
2019-07-05 12:29:02.718815 |
Error in switch(msg$id, DO_CALL = { : EXPR must be a length 1 vector
Calls: <Anonymous>
Execution halted
2019-07-05 12:29:04.329370 |
Error in switch(msg$id, DO_CALL = { : EXPR must be a length 1 vector
Calls: <Anonymous>
Execution halted
2019-07-05 12:29:04.404341 |
Error in switch(msg$id, DO_CALL = { : EXPR must be a length 1 vector
Calls: <Anonymous>
Execution halted
2019-07-05 12:29:04.517879 |
Error in switch(msg$id, DO_CALL = { : EXPR must be a length 1 vector
Calls: <Anonymous>
Execution halted
2019-07-05 12:29:04.850042 |
Error in switch(msg$id, DO_CALL = { : EXPR must be a length 1 vector
Calls: <Anonymous>
Execution halted
----------------------
I ran watch squeue and noticed that workers survived for about 13 seconds. After 13 seconds they quit almost simultaneously.
-----------------------
In my RStudio console I am getting a message:
 in master(qsys = workers, iter = df, rettype = rettype, fail_on_error = fail_on_error,  : 
  Socket timeout reached, likely due to a worker crash
.....
----------------------

**Comment by mschubert** [comment]
Ok, so this is the same error as in the beginning.

Just to make sure, you are still using R>=3.5.2, right?

I still can not reproduce this

**Comment by Zhuk66** [comment]
Yes, we use R 3.5.2
Here is our ulimit -a output:

$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 2062113
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 4096
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

**Comment by Zhuk66** [comment]
I've just noticed:
If I reduce my data size:
  n <-  2000000
  k <- 100
  p <- 100
  mu <- 0
  sigma <- 1
  m <- matrix(data=rnorm(n*k,mu,sigma), nrow=n, ncol=k)
Q function works:
Q(fun, i=1:k, export=list(myFunc=myFunc, m=m), n_jobs=5, timeout=120) 
foreach DOES NOT WORK!
clustermq::register_dopar_cmq(n_jobs=5, timeout=120)
foreach(i = 1:k,
             .inorder=TRUE,
             .combine = 'c',
             .export = c("m", "%dopar%", "myFunc"),
             .packages = "clustermq",
             .verbose=FALSE) %dopar% {
                   myFunc(m[,i])
             }

**Comment by Zhuk66** [comment]
If I use a bigger data object, i.e.  n <- 3000000,
both Q and foreach fail....

**Comment by mschubert** [comment]
I tried to reproduce the following with the following with the current `develop` branch (lots of changes under the hood!):

```r
library(foreach)
myFunc <- function(data) {
    sum(data)
}

  n <-  3000000
  k <- 100
  p <- 100
  mu <- 0
  sigma <- 1
  m <- matrix(data=rnorm(n*k,mu,sigma), nrow=n, ncol=k)

clustermq::register_dopar_cmq(n_jobs=5, timeout=120, memory=20480)
foreach(i = 1:k,
             .inorder=TRUE,
             .combine = 'c',
             .export = c("m", "%dopar%", "myFunc"),
             .packages = "clustermq",
             .verbose=FALSE) %dopar% {
                   myFunc(m[,i])
             }
```

This works without issues for me.

Can you please try this with the current `develop` branch and see if it works for you?

**Comment by mschubert** [comment]
According to https://github.com/mschubert/clustermq/issues/179 this is fixed in `develop`. Please reopen if this is not the case, [including this information](https://github.com/mschubert/clustermq/issues/179#issuecomment-651380351).
